//
//  DietaryInformationView.swift
//  Meal Planner
//
//  Created by Haasini Police on 4/19/24.
//

import Foundation

import SwiftUI
struct DietaryInformationView: View {
    var body: some View {
        VStack {
            Text("DIETARY INFORMATION")
                .foregroundColor(.secondary)
                //.font(.custom("Didot", size: 25))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
                
            Text(" - Recomended intake of protien is 10% to 35% of total daily calories")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 12))
                .bold()
            
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            
            
            Text(" - Recomended intake of calories is 2,000 calories a day for women and 2,500 for men")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 12))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            
            Text(" - Recomended intake of carbs is 45% to 65% of total daily calories")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 12))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            
            Text(" - Recomended intake of fat is 20% to 35% of total daily calories ")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 12))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            
            Text(" - Recomended intake of fiber is 25 to 30 grams daily")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 12))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            
            Text(" - Recomended intake of water is about 11.5 cups a day for women; 15.5 cups for men")
                .foregroundColor(.purple)
           // .font(.custom("Didot", size: 12))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
               
            Text("TIPS FOR EATING HEALTHIER")
                .foregroundColor(.secondary)
               // .font(.custom("Didot", size: 20))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Base your meals on higher fibre starchy carbohydrates")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Eat lots of fruit and vegetables")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Eat more fish, including a portion of oily fish")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Cut down on saturated fat and sugar")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Eat less salt: no more than 6g a day for adults")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Get active and be a healthy weight")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Drink enough water so that you are not dehydrated")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Make sure to eat breakfast")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Try not to eat too much sugar")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Omega-3 Fats Are Crucial and Most People Don’t Get Enough")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - There Is No Perfect Diet for Everyone")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Artificial Trans Fats Are Very Unhealthy")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - It Is Critical to Avoid a Vitamin D Deficiency")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Refined Carbohydrates Are Bad for You")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Supplements Can Never Fully Replace Real Foods")
                .foregroundColor(.purple)
               // .font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
            Text(" - Unprocessed Food Is Healthiest")
                .foregroundColor(.purple)
                //.font(.custom("Didot", size: 15))
                .bold()
                .minimumScaleFactor(0.5)
                .lineLimit(1)
                .multilineTextAlignment(.leading)
        }
    }
}
